version: "3"
services:
  mysql:
    image: mysql
    volumes_from:
      - data_database
    ports:
      - "3306:3306"
    command: mysqld --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: genius
      MYSQL_DATABASE: genius

  data_database:
    image: cogniteev/echo
    command: echo 'Data Container for MySql'
    volumes:
      - /var/lib/mysql

  complaints:
    build:
      context: ./CondoGenius-Complaints-Api
      dockerfile: Dockerfile
    environment:
      TESTE: teste
    volumes:
      - ./gateway:/usr/gateway
    ports:
      - "5002:5002"
