version: "3"
services:
  mysql:
    image: mysql
    volumes_from:
      - data_database
    ports:
      - "3306:3306"
    command: mysqld --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: genius
      MYSQL_DATABASE: genius

  mysql-init:
    image: mysql:latest
    volumes:
      - ./Data/InitializeDatabase.sql:/Data/InitializeDatabase.sql
      - ./Data/InsertCommonArea.sql:/Data/InsertCommonArea.sql
    command: bash -c "sleep 80 && mysql -h mysql -uroot -pgenius genius < Data/InitializeDatabase.sql && mysql -h mysql -uroot -pgenius genius < Data/InsertCommonArea.sql"
    depends_on:
      - mysql

  data_database:
    image: cogniteev/echo
    command: echo 'Data Container for MySql'
    volumes:
      - /var/lib/mysql

  gateway:
    image: gateway
    build:
      context: ./CondoGenius-Gateway-API
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    command: npm start
    volumes:
      - ./gateway:/usr/gateway
    ports:
      - "5000:5000"
    depends_on:
      - mysql


  complaints:
    image: complaints
    build:
      context: ./
      dockerfile: CondoGenius-Complaints-API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:7002
    ports:
      - "7002:7002"

  deliveries:
    image: deliveries
    build:
      context: ./
      dockerfile: CondoGenius-Deliveries-API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:7003
    ports:
      - "7003:7003"

  digital_hub:
    build:
      context: ./CondoGenius-Hub-Digital
      dockerfile: Dockerfile
    environment:
      NODE_ENV: Dockerfile
    command: npm start
    volumes:
      - ./hub_digital:/usr/hub_digital:cached
    ports:
      - "7004:7004"
    depends_on:
      - mysql
  
  checks:
    image: checks
    build:
      context: ./
      dockerfile: CondoGenius-Checks-API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:7005
    ports:
      - "7005:7005"

  reservations:
    image: reservations
    build:
      context: ./
      dockerfile: CondoGenius-Reservations-API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:7006
    ports:
      - "7006:7006"

  residents:
    build:
      context: ./CondoGenius-Residents-Api
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    command: npm start
    volumes:
      - ./residents:/usr/residents:cached
    ports:
      - "7008:7008"
    depends_on:
      - mysql

  meetings:
    build:
      context: ./CondoGenius-Meetings-Api
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    command: npm start
    volumes:
      - ./meetings:/usr/meetings:cached
    ports:
      - "7009:7009"
    depends_on:
      - mysql

  send-notifications:
    build:
      context: ./CondoGenius-SendNotifications
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    command: npm start
    volumes:
      - ./send-notifications:/usr/send-notifications
    ports:
      - "7007:7007"

  condogenius_web:
    image: web
    build:
      context: ./CondoGenius-WEB
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./CondoGenius-WEB:/app

  rabbitmq:
    image: rabbitmq:3-management
    container_name: condogenius-rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"

networks:
  db_network:
    driver: bridge
