version: "3"
services:
  mysql:
    image: mysql
    volumes_from:
      - data_database
    ports:
      - "3306:3306"
    command: mysqld --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: genius
      MYSQL_DATABASE: genius

  data_database:
    image: cogniteev/echo
    command: echo 'Data Container for MySql'
    volumes:
      - /var/lib/mysql

  database-runner:
    build: 
      context: ./migrations
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - data_database

  gateway:
    image: gateway
    build:
      context: ./CondoGenius-API-Gateway
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5000
    ports:
      - "5000:5000"

  complaints:
    image: complaints
    build:
      context: ./CondoGenius-Complaints-API
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:7002
    ports:
      - "7002:7002"

  deliveries:
    image: deliveries
    build:
      context: ./CondoGenius-Deliveries-API
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:7003
    ports:
      - "7003:7003"

  digital_hub:
    image: digital_hub
    build:
      context: ./CondoGenius-DigitalHub-API
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:7004
    ports:
      - "7004:7004"

  reservations:
    image: reservations
    build:
      context: ./CondoGenius-Reservations-API
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:7006
    ports:
      - "7006:7006"

  residents:
    build:
      context: ./CondoGenius-Residents-Api
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    command: npm start
    volumes:
      - ./residents:/usr/residents
    ports:
      - "7008:7008"

  send-notifications:
    build:
      context: ./CondoGenius-SendNotifications
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    command: npm start
    volumes:
      - ./send-notifications:/usr/send-notifications
    ports:
      - "7007:7007"

  condogenius_web:
    image: web
    build:
      context: ./CondoGenius-WEB
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
